#bans
mysql:
  hostname: ''
  port: 3306
  username: ''
  password: ''
  database: 'randompvp'
  table: 'punishments'
server-name: ''
sync-interval: 1m

#anticheat
settings:
    ticksToKill: 10 # Ticks till removal
    amountOfFakePlayers: 16 # Amount to spawn
    invisibility: false # Invisible players or not
    autoBanOnXPlayers: 4 # If someone kills this many, they will be autobanned
    silentBan: false # If false, user will be kicked on ban, always enabled if using a custom command
    randomlyRun: true # Randomly select a player
    min-players-to-autorun: 5 # Minimum players to to the auto check
    runEvery: 2400 # If above is true, how many ticks between each check
    defaultType: "running" # Running or standing style
messages:
    banMessage: "ANTI-AURA: Passed threshold" # Ban message
    kickMessage: "ANTI-AURA: Passed threshold" # Kick message
customBanCommand:
    enable: false
    command: ban %player
player-checks:
    world: true
    max-to-check: 10
    on-pvp:
        enabled: false
        time-delay: 60