main: RandomPvP.Core.RPICore
version: 1.0
name: RPI
author: Randomizer27
database: true
depend: [ProtocolLib]

commands:
  ban:
        description: ban
  kick:
        description: kick
  mute:
        description: mute
  unban:
        description: unban
  unmute:
        description: unmute
  history:
        description: history
  auracheck:
        description: Check if player has aura hack
        usage: /<command> <nickname> (running/standing) (invisible/visible) - checks for aura hack
        aliases: [ac]